DELETE from AnimalDeregister
DELETE from  AnimalExamination        
DELETE from  AssignAnimal;             
DELETE from  AssignAnimalStatus;       
DELETE from  AssignFeed;               
DELETE from  AttachedResource         
DELETE from  Breed;                    
DELETE from  CentralHostRegistration  
DELETE from  DrugsTreatments;          
DELETE from  Facility;                 
DELETE from  Farm;                     
DELETE from  Farmer                   
DELETE from  FeedPattern;              
DELETE from  FeedType;                 
DELETE from  GeneralHealthExamination; 
DELETE from  GeneralHealthObservation; 
DELETE from  MoveBullForHerd;          
DELETE from  OrderSemen;               
DELETE from  RegisterAnimal;         
DELETE from  ResponseOrderSemen;       
DELETE from  SCEvidence;               
DELETE from  SCResource;               
DELETE from  SCSecretKey;            
DELETE from  SCTransaction;           
DELETE from  SemenUtilization;         
DELETE from  TemporaryMovement;      
DELETE from  TemporaryMovementGroup;  
DELETE from  Users;                
