version: '3'
services:
  dsp: 
    build:
        context: .
        dockerfile: dspdockerfile 
    container_name: dsp
    ports:
      - '9000:9000'
    environment:
      - dbip=${dbip}
      - dbuser=${dbuser}
      - dbpassword=${dbpassword}
    restart: unless-stopped
  ipfs: 
    build:
        context: .
        dockerfile: ipfsdockerfile 
    container_name: ipfs
    ports:
      - '4001:4001'
      - '5001:5001'
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - ./data:/home/app/data
  ganache: 
    build:
        context: .
        dockerfile: ganachedockerfile 
    container_name: ganache
    ports:
      - '8545:8545'
    restart: unless-stopped
    volumes:
      - ./data:/home/app/data
